deployment:
  jobBackoffLimit: 5
  replicas: 1
  affinity: {}
  nodeSelector: {}
  tolerations: []
  resources: {}
  memory:
    maxHeapSize: 256M
    heapNewSize: 96M

service:
  type: NodePort
  ports:
    cqlsh:
      nodePort: 31042

pvc:
  storageClassName:
  volumeName:

persistent: true
