deployment:
  jobBackoffLimit: 5
  replicas: 1
  affinity: {}
  nodeSelector: {}
  tolerations: []
  resources: {}

service:
  type: NodePort
  ports:
    cqlsh:
      nodePort: 31042

pvc:
  volumeName:

persistent: true