apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    run: any-proxy
  name: any-proxy
spec:
  selector:
    matchLabels:
      run: any-proxy
  template:
    metadata:
      labels:
        run: any-proxy
    spec:
      containers:
      - image: {{ .Values.ds.image }}
        name: iptables
        securityContext:
          privileged: true
        env:
        - name: "http_proxy"
          value: {{ .Values.global.httpProxy }}
        - name: "https_proxy"
          value: {{ .Values.global.httpsProxy }}
      hostNetwork: true
