apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
{{ include "{{ .Chart.Name }}.labels" . | indent 2 }}
spec:
  sessionAffinity: None
  selector:
    app: {{ .Chart.Name }}
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30003
