deployment:
  jobBackoffLimit: 5
  replicas: 1
  affinity: {}
  nodeSelector: {}
  tolerations: []
  resources: {}

service:
  type: NodePort
  ports:
    mysql:
      nodePort: 31306

pvc:
  storageClassName:
  volumeName:

persistent: true
