{{- if .Values.rbacEnable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "prometheus-operator.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" | lower }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "prometheus-operator.fullname" . }}
{{- end }}
