{{- if .Values.rbacEnable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "prometheus-operator.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" | lower }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "prometheus-operator.fullname" . }}
  annotations:
    "helm.sh/hook": pre-install,post-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
{{- end }}
