{{- if .Values.persistent }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-data
spec: 
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
{{- end }}