{{- if .Values.persistent }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-data
spec: 
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{- if .Values.pvc.volumeName }}
  volumeName: {{ .Values.pvc.volumeName }}
{{- end }}
{{- end }}
