apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-0
{{ include "{{ .Chart.Name }}.labels" . | indent 2 }}
spec:
  selector:
    app: {{ .Chart.Name }}
  type: NodePort
  sessionAffinity: None
  ports:
  - name: cqlsh
    protocol: TCP
    port: 9042
    targetPort: 9042
    nodePort: {{ .Values.service.ports.cqlsh.nodePort }}