apiVersion: v1
name: cilium
version: 1.0.0
appVersion: 1.1.0
description: "Cilium brings API-aware network security filtering to Linux container frameworks like Docker and Kubernetes."
keywords:
- cilium
- network policy
icon: https://thalesgroup.github.io/miniapps/icons/cilium.png
sources:
- https://github.com/thalesgroup/miniapps/tree/master/charts/cilium
maintainers:
- name: cvila
  email: christophe.vila@gemalto.com
- name: jroucheton
  email: jerome.roucheton@gemalto.com