{{- if .Values.persistent }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-data
spec:
{{- if .Values.pvc.storageClassName }}
  storageClassName: {{ .Values.pvc.storageClassName }}
{{- end }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
{{- if .Values.pvc.volumeName }}
  volumeName: {{ .Values.pvc.volumeName }}
{{- end }}
{{- end }}