apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-0
{{ include "{{ .Chart.Name }}.labels" . | indent 2 }}
spec:
  selector:
    app: {{ .Chart.Name }}
  type: NodePort
  sessionAffinity: None
  ports:
  - name: mysql
    protocol: TCP
    port: 3306
    targetPort: 3306
    nodePort: {{ .Values.service.ports.mysql.nodePort }}